name: Build client Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        env:
          CI_REGISTRY_IMAGE: odensc/yatpack-client
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
          cd client
          echo $DOCKER_TOKEN | docker login -u odensc
          docker build -t $CI_REGISTRY_IMAGE:$GITHUB_SHA .
          docker push $CI_REGISTRY_IMAGE:$GITHUB_SHA
          docker tag $CI_REGISTRY_IMAGE:$GITHUB_SHA $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:latest
