name: Build server Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        env:
          CI_REGISTRY_IMAGE: odensc/yatpack-server
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          cd server
          docker login -u odensc -p $DOCKER_TOKEN
          docker build -t $CI_REGISTRY_IMAGE:$GITHUB_SHA .
          docker push $CI_REGISTRY_IMAGE:$GITHUB_SHA
          docker tag $CI_REGISTRY_IMAGE:$GITHUB_SHA $CI_REGISTRY_IMAGE:latest
          docker push $CI_REGISTRY_IMAGE:latest
